apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

#namePrefix: prod-

patches:
- path: configmap.yaml

images:
- name: admin-ui
  newName: admin-ui
  newTag: stable
