apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dataprotection-pvc
spec:
  accessModes:
    - ReadWriteOnce  # Changed from ReadWriteMany to be compatible with local-path
  resources:
    requests:
      storage: 100Mi
  storageClassName: local-path  # Explicitly specify the storage class
