apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-ui
  labels:
    app: admin-ui
spec:
  replicas: 2
  selector:
    matchLabels:
      app: admin-ui
  template:
    metadata:
      labels:
        app: admin-ui
    spec:
      containers:
        - name: admin-ui
          image: ghcr.io/ilroberts/dotnetmodularmonolith/admin-ui:357b600
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: ASPNETCORE_PATHBASE
              value: /admin
            - name: ASPNETCORE_URLS
              value: http://+:8080
            - name: ModularMonolithApiUrl
              valueFrom:
                configMapKeyRef:
                  name: admin-ui-config
                  key: ModularMonolithApiUrl
            - name: TokenServiceUrl
              valueFrom:
                configMapKeyRef:
                  name: admin-ui-config
                  key: TokenServiceUrl
            - name: REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  name: admin-ui-config
                  key: REDIS_HOST
            - name: REDIS_PORT
              valueFrom:
                configMapKeyRef:
                  name: admin-ui-config
                  key: REDIS_PORT
            - name: REDIS_USER
              valueFrom:
                configMapKeyRef:
                  name: admin-ui-config
                  key: REDIS_USER
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: redis-secret
                  key: REDIS_PASSWORD
            - name: REDIS_CONNECTION_STRING
              value: $(REDIS_HOST):$(REDIS_PORT),user=$(REDIS_USER),password=$(REDIS_PASSWORD)
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: admin-ui-config
                  key: OTEL_EXPORTER_OTLP_ENDPOINT
          livenessProbe:
            httpGet:
              path: /HealthCheck
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /HealthCheck
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
          startupProbe:
            httpGet:
              path: /HealthCheck
              port: 8080
            failureThreshold: 30
            periodSeconds: 10
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
